/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expenses.gui;

import expenses.dao.SelfHistoryDAO;
import expenses.pojo.GlobalData;
import expenses.pojo.SelfHistory;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Maraxys
 */
public class ExpenseHistoryFrame extends javax.swing.JFrame {

    /**
     * Creates new form ExpenseHistoryFrame]
     */
    String eTxnId,eCat,eAmt,eDesc,descBox;
    Date eDate;
    public ExpenseHistoryFrame() {
        initComponents();
        super.setLocationRelativeTo(null);
        
        jtSelfExpense.setRowSorter(new TableRowSorter(jtSelfExpense.getModel()) {
    @Override
        public boolean isSortable(int column) {
        return false;
            }
        });
        
        JTableHeader tblHeader=jtSelfExpense.getTableHeader();
        tblHeader.setBackground(Color.black);
        tblHeader.setForeground(Color.white);
        tblHeader.setFont(new Font("Calibri",Font.BOLD,18));
        
        showExpenseDataInTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtSelfExpense = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtAmt = new javax.swing.JTextField();
        txtCat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        btnClear = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setForeground(new java.awt.Color(255, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(48, 48, 48));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 650));

        jPanel3.setBackground(new java.awt.Color(2, 136, 209));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jPanel7.setBackground(new java.awt.Color(255, 0, 0));
        jPanel7.setForeground(new java.awt.Color(255, 0, 0));

        lblLogout.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 978, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 0, 1090, 70));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setFont(new java.awt.Font("Calibri", 0, 28)); // NOI18N

        jtSelfExpense.setAutoCreateRowSorter(true);
        jtSelfExpense.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jtSelfExpense.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jtSelfExpense.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TXN ID", "S. NO.", "DATE", "AMOUNT", "CATEGORY", "DESCRIPTION"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtSelfExpense.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtSelfExpense.setGridColor(new java.awt.Color(255, 255, 255));
        jtSelfExpense.setSelectionBackground(new java.awt.Color(0, 51, 204));
        jtSelfExpense.getTableHeader().setReorderingAllowed(false);
        jtSelfExpense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtSelfExpenseMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtSelfExpense);
        if (jtSelfExpense.getColumnModel().getColumnCount() > 0) {
            jtSelfExpense.getColumnModel().getColumn(0).setMinWidth(0);
            jtSelfExpense.getColumnModel().getColumn(0).setPreferredWidth(0);
            jtSelfExpense.getColumnModel().getColumn(0).setMaxWidth(0);
            jtSelfExpense.getColumnModel().getColumn(1).setMinWidth(60);
            jtSelfExpense.getColumnModel().getColumn(1).setPreferredWidth(60);
            jtSelfExpense.getColumnModel().getColumn(1).setMaxWidth(60);
            jtSelfExpense.getColumnModel().getColumn(2).setMinWidth(125);
            jtSelfExpense.getColumnModel().getColumn(2).setPreferredWidth(125);
            jtSelfExpense.getColumnModel().getColumn(2).setMaxWidth(125);
            jtSelfExpense.getColumnModel().getColumn(3).setMinWidth(100);
            jtSelfExpense.getColumnModel().getColumn(3).setPreferredWidth(100);
            jtSelfExpense.getColumnModel().getColumn(3).setMaxWidth(100);
            jtSelfExpense.getColumnModel().getColumn(4).setMinWidth(175);
            jtSelfExpense.getColumnModel().getColumn(4).setPreferredWidth(175);
            jtSelfExpense.getColumnModel().getColumn(4).setMaxWidth(175);
            jtSelfExpense.getColumnModel().getColumn(5).setPreferredWidth(15);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 760, 300));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("My Transaction History");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(107, 107, 107))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 930, 60));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Date");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, -1));

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 153));
        jLabel3.setText("Amount");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, -1));

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 153));
        jLabel4.setText("Category");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 90, -1));

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 153));
        jLabel5.setText("Description");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txtDate.setEditable(false);
        txtDate.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        jPanel5.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 140, 40));

        txtAmt.setEditable(false);
        txtAmt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmtActionPerformed(evt);
            }
        });
        jPanel5.add(txtAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 140, 40));

        txtCat.setEditable(false);
        txtCat.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCatActionPerformed(evt);
            }
        });
        jPanel5.add(txtCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 140, 40));

        txtDesc.setEditable(false);
        txtDesc.setColumns(20);
        txtDesc.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtDesc.setLineWrap(true);
        txtDesc.setRows(5);
        txtDesc.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDesc);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 250, 60));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 290, 300));

        btnClear.setBackground(new java.awt.Color(255, 0, 153));
        btnClear.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 170, 40));

        btnModify.setBackground(new java.awt.Color(0, 0, 255));
        btnModify.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnModify.setForeground(new java.awt.Color(255, 255, 255));
        btnModify.setText("MODIFY TRANSACTION");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        jPanel1.add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 620, 290, 50));

        lblBack.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        lblBack.setForeground(new java.awt.Color(51, 51, 51));
        lblBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBack.setText("Go Back");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        jPanel1.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 48));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        // TODO add your handling code here:
        PersonalExpenseFrame personal = new PersonalExpenseFrame();
        personal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void jtSelfExpenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtSelfExpenseMouseClicked
        // TODO add your handling code here:
        //String descBoz="";
        int row = jtSelfExpense.getSelectedRow();
        TableModel model = jtSelfExpense.getModel();
        txtDate.setText(model.getValueAt(row, 2).toString());
        txtAmt.setText(model.getValueAt(row, 3).toString());
        txtCat.setText(model.getValueAt(row, 4).toString());
        if(model.getValueAt(row, 5)==null)
            descBox="";
        else
            descBox=model.getValueAt(row, 5).toString();
        txtDesc.setText(descBox);
    }//GEN-LAST:event_jtSelfExpenseMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtDate.setText("");
        txtAmt.setText("");
        txtCat.setText("");
        txtDesc.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
        if (txtDate.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Please Select a Record", "Error", JOptionPane.ERROR_MESSAGE);
            return;

        }
        int row = jtSelfExpense.getSelectedRow();
        TableModel model = jtSelfExpense.getModel();
        
        eTxnId=model.getValueAt(row, 0).toString();
        eDate=(Date) model.getValueAt(row, 2);
        eAmt=txtAmt.getText();
        eCat=txtCat.getText();
        eDesc=txtDesc.getText();
        
        GlobalData.setOldCat(eCat);
        GlobalData.setOldAmt(Integer.parseInt(eAmt));
        
       
         InputCalculatorFrame ic=new InputCalculatorFrame(eTxnId,eCat,eAmt,eDesc,eDate);
         ic.setVisible(true);
         this.dispose();

    }//GEN-LAST:event_btnModifyActionPerformed

    private void txtAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmtActionPerformed

    private void txtCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCatActionPerformed

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
        int ans=JOptionPane.showConfirmDialog(null, "Are you Sure you want to Logout??","Confirm Logout",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {
        UserLoginFrame loginfrm=new UserLoginFrame();
        loginfrm.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_lblLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExpenseHistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExpenseHistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExpenseHistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExpenseHistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExpenseHistoryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnModify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtSelfExpense;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JTextField txtAmt;
    private javax.swing.JTextField txtCat;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextArea txtDesc;
    // End of variables declaration//GEN-END:variables

    private void showExpenseDataInTable() {
        try {
            ArrayList<SelfHistory> selfTxList = SelfHistoryDAO.getExpenses(GlobalData.getUsername());

            if (selfTxList.isEmpty()) {

            } else {
                DefaultTableModel model = (DefaultTableModel) jtSelfExpense.getModel();
                Object[] row = new Object[6];                           //It shows the number of columns in the table i.e. 6 in our case
                int count = 1;
                for (SelfHistory obj : selfTxList) {
                    row[0] = obj.getTxid();
                    row[1] = count;
                    row[2] = obj.getDate();
                    row[3] = obj.getExpense();
                    row[4] = obj.getCategory();
                    row[5] = obj.getDesc();
                    model.addRow(row);
                    count++;
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "SQL Query Error in Table", "Error in Table!", JOptionPane.ERROR_MESSAGE);
        }
    }
}
